kind: pipeline
name: go1.13

services:
  - name: etcd
    image: bitnami/etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: yes
  - name: redis
    image: bitnami/redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes
  - name: consul
    image: bitnami/consul
  - name: zookeeper
    image: bitnami/zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

steps:
  - name: test
    image: golang:1.13
    environment:
      ETCD_ENDPOINTS: "etcd:2379"
      REDIS_ADDR: "redis:6379"
      CONSUL_ADDR: "consul:8500"
      ZOOKEEPER_ENDPOINTS: "zookeeper"
    commands:
      - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov-token
      files:
        - coverage.txt

---
kind: pipeline
name: go1.12

services:
  - name: etcd
    image: bitnami/etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: yes
  - name: redis
    image: bitnami/redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes
  - name: consul
    image: bitnami/consul
  - name: zookeeper
    image: bitnami/zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

steps:
  - name: test
    image: golang:1.12
    environment:
      ETCD_ENDPOINTS: "etcd:2379"
      REDIS_ADDR: "redis:6379"
      CONSUL_ADDR: "consul:8500"
      ZOOKEEPER_ENDPOINTS: "zookeeper"
    commands:
      - go test -race -v ./...

---
kind: pipeline
name: go1.11

services:
  - name: etcd
    image: bitnami/etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: yes
  - name: redis
    image: bitnami/redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes
  - name: consul
    image: bitnami/consul
  - name: zookeeper
    image: bitnami/zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

steps:
  - name: test
    image: golang:1.11
    environment:
      ETCD_ENDPOINTS: "etcd:2379"
      REDIS_ADDR: "redis:6379"
      CONSUL_ADDR: "consul:8500"
      ZOOKEEPER_ENDPOINTS: "zookeeper"
    commands:
      - go test -race -v ./...

---
kind: pipeline
name: lint

steps:
  - name: lint
    image: golang
    commands:
      - go get -u github.com/mgechev/revive
      - revive -formatter=friendly -config=revive.toml -exclude=vendor/... ./...
